# Generated by Django 3.2.8 on 2022-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=255, null=True)),
                ('facilityNo', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('completionDate', models.DateField(null=True)),
                ('landArea', models.CharField(max_length=255, null=True)),
                ('buildingArea', models.CharField(max_length=255, null=True)),
                ('totalBuildingArea', models.CharField(max_length=255, null=True)),
                ('highestHeight', models.CharField(max_length=255, null=True)),
                ('Usage', models.CharField(max_length=255, null=True)),
                ('facilityStructure', models.CharField(max_length=255, null=True)),
                ('structuralForm', models.CharField(max_length=255, null=True)),
                ('amenities', models.CharField(max_length=255, null=True)),
                ('floors', models.CharField(max_length=255, null=True)),
                ('grade', models.CharField(max_length=255, null=True)),
                ('testResults', models.CharField(max_length=255, null=True)),
                ('plus', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
