# Generated by Django 3.2.8 on 2022-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='frontView',
            field=models.ImageField(null=True, upload_to='images/frontView/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='locationMap',
            field=models.ImageField(null=True, upload_to='images/locationMap/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='facilityName',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
