# Generated by Django 3.2.8 on 2022-01-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220101_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='facilityName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Crack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/crack_img/origin/%Y/%m/%d/')),
                ('flatting_image', models.ImageField(null=True, upload_to='images/crack_img/flatting/%Y/%m/%d/')),
                ('isFlattened', models.BooleanField(default=False)),
                ('originWidth', models.FloatField(null=True)),
                ('originHeight', models.FloatField(null=True)),
                ('crackLength', models.FloatField(null=True)),
                ('floor', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('absence', models.CharField(max_length=255, null=True)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=255, null=True)),
                ('progress', models.CharField(max_length=255, null=True)),
                ('cause', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
    ]
